### ISSUE TITLE
Session does not send a GET after a POST

### ISSUE THREAD

**Issue by miguelpuyol** [lihaoyi/requests-scala#1]
Hi @lihaoyi !

I tested your new library and it's great to see the simplicity of the Python requests coming to the Scala world.

However, I faced an issue when emulating a simple python script that uses requests.

Scenario: 

1. Execute a POST to store the cookies for future requests
2. Execute a GET using the cookie from the previous request

Unfortunately, the Session class (or its underlying connection) keeps a state that prevents the second request to be a GET. It sends a POST.

I created a Jupiter-Scala notebook that relies on Netcat and reproduces this scenario.

[Scala Requests - Bug.ipynb.zip](https://github.com/lihaoyi/requests-scala/files/2213626/Scala.Requests.-.Bug.ipynb.zip)

Thanks for all your work!

**Comment by lihaoyi** [comment]
the long and short is you cannot use `data` when making a get, you have to use `params` and pass in a map. This is the same as the original Python requests, except they choose to ignore the data attribute
