### ISSUE TITLE
Post访问页面出现的一些问题

### ISSUE THREAD

**Issue by dhdsjy** [lihaoyi/requests-scala#13]
您好，在使用requests-scala时遇到一些问题，不知能否帮忙看下：
val map_data = Map("ids"->"123456789","deal_type"->1）
val r = requests.post(url, data = map_data)
一直编译不通过，后来发现是Map里面的类型不一致？这个问题有想过怎么解决吗 
小白只会用轮子。。

**Comment by sadhen** [comment]
see https://github.com/lihaoyi/requests-scala/blob/89b7b6c7761274d27144bb03c5da7984af476263/requests/src/requests/Requester.scala#L71

这里的Post Body的类型是 `Iterable[(String, String)]`。所以你应该用 `Map("a" -> "b", "c", "1")`这种形式。推荐看一看这边的代码清单： https://github.com/ReactivePlatform/Pragmatic-Scala  系统学习一下Scala这门语言。

Well, please close this issue.
