### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by hongee** [lihaoyi/requests-scala#16]
Hi there! I'm new-ish to Scala, and was poking around at this to try and learn a thing or two :) Annoyingly I couldn't get the library to build and the tests to run (using mill), and the options offered from `mill resolve __` or `mill resolve requests._` or even `mill resolve tests._` don't seem to work. Would you mind sharing the incantations to get this to run?

Thanks! :D

**Comment by lihaoyi** [comment]
you can ask mill questions in the mill gitter channel
