### ISSUE TITLE
Customize compiler message

### ISSUE THREAD

**Issue by sadhen** [lihaoyi/requests-scala#21]
Reflections on #13 .

I'm wondering if we have the ability to customize the compiler error message:

```
scala> val a: Map[String, String] = Map("a" -> 1)
<console>:11: error: type mismatch;
 found   : Int(1)
 required: String
       val a: Map[String, String] = Map("a" -> 1)
                                               ^
```

I remember there are compiler plugins (https://github.com/softwaremill/scala-clippy) to improve the compiling messages.

It would be great if a scala library generate easy to read error messages for newbies.

Some thoughts when I'm writing https://github.com/ReactivePlatform/ScalaScripting/blob/master/http/get.sc

**Comment by hepin1989** [comment]
It a plugin from softwaremills

**Comment by lihaoyi** [comment]
gonna call this a wontfix by myself; feel free to pursue it and send a PR if you wis
