### ISSUE TITLE
Add example to POST JSON

### ISSUE THREAD

**Issue by pathikrit** [lihaoyi/requests-scala#23]
When we submit `data = Map` we get a form submission; if it is a JSON encoded as String, we get the wrong header. It would be helpful if the README included an example of submitting a JSON to a JSON API

**Comment by liancheng** [comment]
The wrong header issue should have been fixed by #26 (assuming that you meant the "Content-Type" header set to "text/plain").

**Comment by pathikrit** [comment]
I don't understand - how do I submit a json? Submit a Map and set `content-type = application/json`??

**Comment by liancheng** [comment]
@pathikrit Submit a JSON string and set "Content-Type" to "application/json". I personally prefer using the `ujson` library to simplify the JSON string construction:

```scala
import $ivy.`com.lihaoyi::requests:0.1.7`
import $ivy.`com.lihaoyi::ujson:0.7.1`

import ujson._

requests.post(
  url = "https://httpbin.org/post",
  headers = Map("Content-Type" -> "application/json"),
  data = Obj(
    "hello" -> "world",
    "this" -> Arr("is", "an", "array")
  ).render()
)
```

**Comment by aamir-f** [comment]
I am making a simple post call:

val response = requests.post(
      url,
      headers = Map("accept" -> "application/json"),
      data = json)

my json is :{"password":"password","username":"username"}

The response is throwing Bad Request 400
I am hitting the same post service from my postman, its working fine.

**Comment by royki** [comment]
@pathikrit You can do it following way as well - 
```scala
import requests._
import ujson._

// headers
val allHeaders = Map(
      "x-api-key" -> x-api-key
    "Authorization" -> authorization,
    "Accept" -> "application/json",
    "Content-Type" -> "application/json"
)

// some Json Object 
import ujson._
val userJsonReq = Js.Obj(
    "login" -> s"$randomStr@yopmail.com",
    "password" -> s"$randomStr",
    "phoneNumber" -> s"$phone",
    "email" -> s"$randomStr@yopmail.com",
    "firstName" -> "Name",
    "lastName" -> "LastName",
    "gender" -> "female",
    "address" -> Js.Obj(
      "streetAddress" -> s"$address",
      "locality" -> "Lo",
      "postalCode" -> "XXXX",
      "region" -> "NA",
      "country" -> "US"    
 )
)

// Post Request with headers and request body

val createUser = requests.post(
   url = "https://www.yourapi.com",
   headers = allHeaders,
   data = userJsonReq.toString
)

val json = ujson.read(createUser.text())
println(json)
```

**Comment by lihaoyi** [comment]
You can now skip the `.render` call:

```scala
requests.post(
  "https://api.github.com/some/endpoint",
  data = ujson.Obj("user-agent" -> "my-app/0.0.1")
)
```
