### ISSUE TITLE
requests.get cannot accept two parameters

### ISSUE THREAD

**Issue by ShutaoTang** [lihaoyi/requests-scala#3]
When I run the following code in IDEA REPL:
 
    val r = requests.get(
      "https://api.github.com/search/repositories",
      params = Map("q" -> "http language:scala", "sort" -> None)
    )

The IDEA shows that "Cannot resolve symbol get". 

    found   : None.type
    required: String
         params = Map("q" -> "http language:scala", "sort" -> None)
                                                              ^

**Comment by kiviok** [comment]
I think it's a typo in README. Try to replace "sort" -> "stars", or nothing for default best match.
https://developer.github.com/v3/search/#parameters

**Comment by ShutaoTang** [comment]
OK, got it. Thanks:)

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/requests-scala/pull/4
