### ISSUE TITLE
Is throwing Exceptions the new thing now?

### ISSUE THREAD

**Issue by andreak** [lihaoyi/requests-scala#53]
Hi.
After updating to 0.5 (from 0.2 or so) lots of code is failing due to Exceptions being thrown instead of returning `Response` with the proper values for the failuer.
Is this documented anywhere?

**Comment by Magua** [comment]
There is this in the changelog:
### 0.4.7

- `requests.{get,post,put,delete,head,options,patch}` now throw a
  `requests.RequestFailedException(val response: Response)` if a non-2xx status
  code is received. You can disable throwing the exception by passing in
  `check = false`

But what about 301, 302 redirects, should probably be excluded.

**Comment by andreak** [comment]
Right, thanks.
Is "check = false" the official way to not having the library throwing an Exception on 4xx/5xx, and considered stable?

**Comment by Magua** [comment]
I would say yes, since it is in the changelog from 0.4.7. Personally I would have liked to see `check = false` the default behaviour.
