### ISSUE TITLE
requests.get.stream forces use of var

### ISSUE THREAD

**Issue by andreak** [lihaoyi/requests-scala#54]
(I tried gitter but no response...)

Hi
I'm feeling that the way this library is going forces me to use `var` more than it should.
If reading a stream from GET I have to use a `var` to store the `StreamHeaders` value and then only read from the stream if response is SC_OK, like this:
```scala
var responseHeaders: Option[StreamHeaders] = None
requests.get.stream("https://some.url", check = false
    , onHeadersReceived = streamHeaders => {
        responseHeaders = Some(streamHeaders)
        if (streamHeaders.statusCode == HttpServletResponse.SC_OK) {
            // stuff
        } else {
            // other stuff
        }
    }).readBytesThrough{ inputStream =>
    if (responseHeaders.exists(_.statusCode == HttpServletResponse.SC_OK)) {
        // read stream
    } else {
        // don't
    }
}
```

It would be great if one could do this to access streamHeaders in the Readable:
```scala
val readable = requests.get.stream("https://some.url", check = false
    , onHeadersReceived = streamHeaders => {
        if (streamHeaders.statusCode == HttpServletResponse.SC_OK) {
            // stuff
        } else {
            // other stuff
        }
    })
if (readable.streamHeaders.statusCode == HttpServletResponse.SC_OK) {
    readable.readBytesThrough{ inputStream =>
        // read stream
    }
}
```

**Comment by lihaoyi** [comment]
Not likely to happen, as Readable does/should not know about headers of HTTP. You can write your own helper to tidy up the code if you want, but `.stream` is fundamentally meant to be a pretty low-level API that involves getting your hands dirty

**Comment by andreak** [comment]
How do you propose processing `readBytesThrough`'s inputStream honoring different `statusCode`s?
