### ISSUE TITLE
Content-Type not inferred as application/json

### ISSUE THREAD

**Issue by Jasper-M** [lihaoyi/requests-scala#55]
```
requests.post(
  url = "http://www.example.com", 
  data = ujson.Obj("foo" -> "bar")
)
```

Given that `data` accepted a `ujson.Value` value I expected `Content-Type` to be `application/json` but it was `application/octet-stream`.

This can be worked around but it's a slight inconvenience. The readme also makes no mention of that limitation.

**Comment by lihaoyi** [comment]
Should work now on the latest versions of things
