### ISSUE TITLE
Explicitly mention how to import library in README

### ISSUE THREAD

**Issue by shenryHen** [lihaoyi/requests-scala#58]
I had a hard time figuring out how to import this library in the first place because I thought I should import it like this:
```import com.lihaoyi.requests```

But I know realize its just this:
```import requests```.

Can we put this in the example code, in the same code block that contains all of the `get`, `post`, etc. examples?

**Comment by lihaoyi** [comment]
there are no imports in this library. You just use `requests.get`

**Comment by bebound** [comment]
I'm a Scala newbie, just out of curiosity, how could this happened?(not need to import for this package)
